import Head from 'next/head'
import Link from 'next/link'
import React, { FC, useRef, useState } from 'react'
import { logIn } from '../helpers/auth'
import { InputText } from 'primereact/inputtext'
import { Card } from 'primereact/card'
import { Button } from 'primereact/button'
import { useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from "yup";
import { Toast } from 'primereact/toast'
import gql from 'graphql-tag'
import { useMutation } from '@apollo/client'

const REGISTER = gql`
  mutation Register($name: String, $email: String!, $password: String!, $passwordConfirmation: String!) {
    register(input: { name: $name email: $email, password: $password, password_confirmation: $passwordConfirmation }) {
      id
      name
      email
      role
    }
  }
`;

type RegisterData = {
  name: String;
  email: string;
  password: string;
  password_confirmation: string;
}

const schema = yup.object().shape({
  name: yup.string().nullable().notRequired().max(255),
  email: yup.string().email().max(255).required(),
  password: yup.string().min(12).required().matches(
    /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]/,
    "Password must contain at least one uppercase, one lowercase, one number and one special case character"
  ),
  password_confirmation: yup.string().oneOf([yup.ref('password'), null], "Password confirmation doesn't match")
});

export default function Register() {
  const [loading, setLoading] = useState(false)
  const toast = useRef<Toast>(null);
  const { register, handleSubmit, formState: { errors } } = useForm({
    resolver: yupResolver(schema)
  })

  const [registerUser] = useMutation(REGISTER, {
    onError(error) {
      setLoading(false)
      toast.current?.show({ severity: 'error', summary: 'Error Message', detail: error })
    },
    onCompleted(data) {
      setLoading(false)
      logIn(data.register)
    }
  })

  const onSubmit = (data: RegisterData) => {
    setLoading(true)
    registerUser({ variables: { name: data.name, email: data.email, password: data.password, passwordConfirmation: data.password_confirmation } })
  }

  const RegisterCardFooter: FC = () => {
    return (
      <div className="p-field p-d-flex p-jc-center">
        <Link href="/login">Already have an account?</Link>
      </div>
    )
  }

  const getFormErrorMessage = (name: string) => {
    return errors[name] && <small className="p-error">{errors[name].message}</small>
  };

  return (
    <div className="d-flex flex-grow-1">
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container d-flex flex-grow-1 mb-3">
        <div className="row flex-grow-1 justify-content-center align-items-center">
          <Card title='Register' footer={RegisterCardFooter} className="col-12 col-md-9 col-lg-6 col-xl-4">
            <form onSubmit={handleSubmit(onSubmit)} className="p-fluid">
              <div className="p-field">
                <label htmlFor="name">Name</label>
                <InputText id="name" type="text" {...register("name")} />
                {getFormErrorMessage('name')}
              </div>
              <div className="p-field">
                <label htmlFor="email">Email address</label>
                <InputText id="email" type="email" {...register("email")} />
                {getFormErrorMessage('email')}
              </div>
              <div className="p-field">
                <label htmlFor="password">Password</label>
                <InputText id="password" type="password" {...register("password")} />
                {getFormErrorMessage('password')}
              </div>
              <div className="p-field p-mb-5">
                <label htmlFor="password_confirmation">Confirm Password</label>
                <InputText id="password_confirmation" type="password" {...register("password_confirmation")} />
                {getFormErrorMessage('password_confirmation')}
              </div>
              <Button label="Register" iconPos="right" loading={loading} />
            </form>
          </Card>
        </div>
        <Toast ref={toast} />
      </main>
    </div>
  )
}
